### ISSUE TITLE
in header, remove KEEP UP TO DATE

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#18]
if this is done could also fix unbalanced lefthand big #NEWPALMYRA logo.

make the subscribe form input a bit longer and then put the text KEEP UP TO DATE in the placeholder of that html button.

make sense?

**Comment by pianoBrad** [comment]
We still want to do this with the tag inserted below the logo?  I've removed keep up to date on mobile displays, but might be more balanced now with the new tag in place for larger displays?
