### ISSUE TITLE
need a call for participation / action section

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#3]
we really looking for contributors of all sorts, developer, 3D modellers and artists in particular. Also, we want researchers in. All else fails: info@newpalmyra.org

**Comment by mlinksva** [comment]
Bullets aren't the best, but anyway, a bullet-blurb for a Get Involved or similar section....

-------

Join us in making #NewPalmyra reality. We're looking for contributors of all sorts: 3D modelers, archaeologists, artists, curators, developers, educators, journalists, researchers, wikimedians. You can do now:

* Meet us in Paris Oct 30-31 at the #ProtoCultural #NewPalmyra hackfest
* Talk to us realtime, #newpalmyra on freenode IRC
* Issues, code, data in our GitHub projects
* Email us info@newpalmyra.org
* Follow us and spread the word on our Facebook, Instagram, Twitter
* Subscribe to our email newsletter
* Contribute info and media about Palmyra to Wikimedia Commons, Wikipedia, etc; we freely use these materials and will contribute more back.

**Comment by rejon** [comment]
Yes, this is important.

**Comment by rejon** [comment]
The section should be below About and be Call for Participation

**Comment by rejon** [comment]
Yes, this should now go below the download button section and before people in its own section with a title: CALL FOR PARTICIPATION
