### ISSUE TITLE
remove .html from project pages, improve human readability + SEO

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#38]
Easier for people to remember, better for seo:

http://www.newpalmyra.org/projects/craft-grid.html

should become:

http://www.newpalmyra.org/projects/craft-grid/index.html

**Comment by rejon** [comment]
Actually for models pages too:

http://www.newpalmyra.org/models/temple-of-bel.html

**Comment by christopheradams** [comment]
Fixed in 63e1527 and fb8f2c5
