### ISSUE TITLE
project pages should have button to github repos

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#41]
http://www.newpalmyra.org/projects/asad-al-lat.html for example should have a github repo on newpalmyra with button to it

**Comment by rejon** [comment]
Bump

**Comment by christopheradams** [comment]
For all [models]:

- [ ] find the repo link on [github]
- [ ] add a `source_url: https://github.com/newpalmyra/...` link to the Jekyll frontmatter

On the design side:
- [ ] add custom layout for projects which will display the GitHub URL 

[models]: https://github.com/newpalmyra/newpalmyra.org/tree/gh-pages/_models
[github]: https://github.com/newpalmyra/newpalmyra.org

**Comment by rejon** [comment]
Like this one and other like it low hanging fruit

**Comment by mlinksva** [comment]
Done.
