### ISSUE TITLE
convert site to https

### ISSUE THREAD

**Issue by rejon** [newpalmyra/newpalmyra.org#68]
to be inline with google recommendations...I believe cloudflare offers something like this already for free, and/or with letsencrypt...seems recommended way is using cloudflare if this site is to stay on github

**Comment by rejon** [comment]
Can do with letsencrypt now for fun and free.

**Comment by christopheradams** [comment]
Evaluate the following:

-[ ] create a Cloudflare account and set it up with [GitHub pages]
-[ ] go back to hosting the site ourselves (which server?), and set it up with letsencrypt. add a hook so pushes here will create a build.

[GitHub pages]: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by rejon** [comment]
Is it possible to do https without hosting selves? Prefer to not host ourselves unless absolutely necessary and there is a growth model for the project.

**Comment by christopheradams** [comment]
> Is it possible to do https without hosting selves?

Already mentioned Cloudflare.

**Comment by rejon** [comment]
waiting

**Comment by rejon** [comment]
@mlinksva is this possible now?

**Comment by mlinksva** [comment]
[Cloudflare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) is still the way to do it if served by GitHub Pages.

**Comment by mlinksva** [comment]
New option https://fly.io/app/sign-up/wizard/github_page via https://twitter.com/bkeepers/status/941431432672661504

Imagine [free for the first 2 million requests and 100GB of data per month](https://fly.io/pricing/) would be adequate.

**Comment by rejon** [comment]
this is possible now. I will move the domain to cloudflare.

**Comment by rejon** [comment]
done
