### ISSUE TITLE
Add a help wanted landing page with instructions

### ISSUE THREAD

**Issue by christopheradams** [newpalmyra/newpalmyra.org#73]
Needs comprehensive instructions based on people's background, what to work on and how to communicate with the project.

**Comment by rejon** [comment]
Ok, /methinks should channel all this to the email info@newpalmya.org and this https://newpalmyra.slack.com

Or, leave the "Contribute" section alone on the main page.

**Comment by rejon** [comment]
scrap slack. its stupid. SHould just have discussion on twitter publicly.

**Comment by rejon** [comment]
fixed
