### ISSUE TITLE
Improve site blurb

### ISSUE THREAD

**Issue by mlinksva** [newpalmyra/newpalmyra.org#8]
Along with #7 the blurb should be improved. Currently

> #NewPalmyra is a project to share data collected about the past and present, to make the future New Palmyra.

Is this just a data project? Or a crazy project to build a new city which will never happen? IIUC it's about a lot more than data and its aims are cultural.

**Comment by rejon** [comment]
Its about combining our 3d models with others 3d models, and continuing to
improve that data, and then provide access and improvingly good services to
make new palmyra creations by artists, and more...

definitely not fake city project and definitely not just data sharing.
however, the contract to allow for collaboration is CC ZERO SHARING OF ALL
DATA BETWEEN PARTNERS.

Jon

**Comment by mlinksva** [comment]
Alright here's my suggestion for site blurb then:

   Sharing data, code, and art for the past, present, and future of Palmyra

Note it ought #7 go under the wordmark #NewPalmyra so don't need to repeat that.

**Comment by rejon** [comment]
Totally.

**Comment by mlinksva** [comment]
Alright will leave to @pianoBrad to implement and close.
