### ISSUE TITLE
site can't be edited!

### ISSUE THREAD

**Issue by barrythrew** [newpalmyra/newpalmyra.org#81]
When trying to compile the site from the last working commit I get an error message:
`Liquid Exception: undefined method `+' for nil:NilClass in
/_layouts/default2.html

jekyll 3.4.3 | Error:  undefined method `+' for nil:NilClass`

Makes the site currently uneditable.

**Comment by christopheradams** [comment]
Running a trace helped:

```
bundle exec jekyll serve --verbose --trace
```

```
  Rendering Layout: _models/template.html
  Liquid Exception: undefined method `+' for nil:NilClass in /_layouts/default2.html
...error:
             Error: undefined method `+' for nil:NilClass
             Error: Run jekyll build --trace for more information.
```

The culprit was the Jekyll SEO plugin. It started crashing on the `title: ""` in the model template.

I unpublished the template so that it doesn't show up in the models list, rather than filtering on the empty title.
