### ISSUE TITLE
#PROTOCULTURAL #NEWPALMYRA event

### ISSUE THREAD

**Issue by mlinksva** [newpalmyra/newpalmyra.org#9]
Blurb for/link to http://protocultural.org/#paris

**Comment by mlinksva** [comment]
Could be just in #3 but seems important enough to merit own section/story or whatever it is called.

**Comment by rejon** [comment]
Yes, good, we should have some connection here, but not ready to launch. I like #NEWPALMYRA and then #PROTOCULTURAL as using...

**Comment by barrythrew** [comment]
depricated
